### ISSUE TITLE
swaggomnia installation issue

### ISSUE THREAD

**Issue by kkashyap1707** [Fyb3roptik/swaggomnia#1]
### Expected behavior
swaggomnia --help command should be working.

### Current behavior
swaggomnia --help command is not working.

### Steps to reproduce the behavior
Install the swaggomnia using wget https://jrpublic.s3-us-west-2.amazonaws.com/linux/1.0.1/swaggomnia 
chmod +x swaggomnia
run command swaggomnia --help

Message displayed : Command not found.

OS : Ubuntu 18.04

Attaching the screenshot for references.
![Screenshot from 2019-06-06 14-07-39](https://user-images.githubusercontent.com/4715140/59019052-e44efe00-8864-11e9-9f51-9b42660ef7d1.png)

![Screenshot from 2019-06-06 14-08-13](https://user-images.githubusercontent.com/4715140/59019049-e3b66780-8864-11e9-8492-89d6f5e1f1fc.png)

**Comment by kkashyap1707** [comment]
My bad, I think few of the Installation steps are missing.

![Screenshot from 2019-06-06 14-27-00](https://user-images.githubusercontent.com/4715140/59020228-2e38e380-8867-11e9-93d9-442cd9d8c56d.png)

**Comment by Fyb3roptik** [comment]
Ah yes sorry about this. I will review installation steps and update as needed. Just moved this repo over! Thanks for using it!
