### ISSUE TITLE
[help] installation steps

### ISSUE THREAD

**Issue by GLuchtenberg** [Fyb3roptik/swaggomnia#11]
Hey, 
I couldn't find the installation steps, could someone help me? :)

**Comment by samair** [comment]
It is a simple binary..

- download the zip/archive
- Extract it, add the executable (swaggomnia) to path
Thats it!

**Comment by arctouch-gabrielluchtenberg** [comment]
tks

**Comment by Fyb3roptik** [comment]
It is similar to downloading any App for your OS
