### ISSUE TITLE
yaml: line 29: found character that cannot start any token

### ISSUE THREAD

**Issue by selique** [Fyb3roptik/swaggomnia#13]
https://github.com/Fyb3roptik/swaggomnia/blob/f0ef8ae8f4981d58875b6ac2d7d53b20996dcb76/tmpl/swagger.yaml#L29

on windows i recive this erro 

`PS C:\Users\judeu\Projetos>  .\swaggomnia.exe generate --insomnia .\teg\docs\Insomnia_API.json --config .\config.json --output json  
2020/04/02 02:46:32 yaml: line 29: found character that cannot start any token`

**Comment by samair** [comment]
Hi Selique,
Is it the case that you see this only for json output.
Could you try with "--output yaml" and let me know.
