### ISSUE TITLE
How to install on Windows 

### ISSUE THREAD

**Issue by Tumi-D** [Fyb3roptik/swaggomnia#14]
Could you please provide instructions on how to install on windows ? I can't seem to find the swaggomonia.exe file.

**Comment by Fyb3roptik** [comment]
Check the releases section. It should have an exe file.

**Comment by Fyb3roptik** [comment]
https://github.com/Fyb3roptik/swaggomnia/releases/download/2.0.1/swaggomnia_windows_amd64.zip
