### ISSUE TITLE
Some requests not reflecting to swagger.json generated file

### ISSUE THREAD

**Issue by andreescocard** [Fyb3roptik/swaggomnia#17]
**Describe the bug**
After exporting on Insomnia v4 json format and generating the json with Swaggomnia, some requests are missing.

**Expected behavior**
I expected to see all requests. Another problem is that parameters are not being exported on requests.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 2.0.1

**Comment by suathh** [comment]
same issue in here
