### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by ghost** [Fyb3roptik/swaggomnia#18]
I am trying to convert a insomiav4 import file to Open API spec YAML using this command:
```shell
./swaggomnia generate -insomnia "test.json" -output yaml
```
It is showing this error
```
2021/05/04 13:37:32 open: no such file or directory
```

**To Reproduce**
1. Get a ubuntu 20.04 installed desktop
2. Create an insomnia v4 import file name it test.json
3. Put the release build binary file "swaggomnia" in the same folder. 
4. Run this command `./swaggomnia generate -insomnia "test.json" -output yaml`
5. TADA you can see the error now `2021/05/04 13:37:32 open: no such file or directory`

**Expected behavior**
It should generate An Open API spec file in YAML format 

**Screenshots**
![Screenshot](https://i.ibb.co/ZM1WPf1/Screenshot-from-2021-05-04-13-43-58.png) 

**Desktop**
 - OS Ubuntu 20.04

**Comment by samair** [comment]
Though a usage issue, the response could be better.
Check
https://github.com/Fyb3roptik/swaggomnia#how-to-use-it
You missed providing `-config` option

`$ swaggomnia generate -insomnia INSOMNIA_EXPORTED_FILE -config CONFIG_FILE -output FORMAT`
