### ISSUE TITLE
Not able to geerate json file

### ISSUE THREAD

**Issue by kkashyap1707** [Fyb3roptik/swaggomnia#2]
### Expected behavior
Json file should be generated

### Current behavior
 yaml: line 15: did not find expected key

### Steps to reproduce the behavior
swaggomnia generate -i Insomnia_2019-06-06.json -c config.json -o json

![Screenshot from 2019-06-06 16-20-28](https://user-images.githubusercontent.com/4715140/59027640-31d46680-8877-11e9-875c-90fc8e945693.png)

**Comment by Fyb3roptik** [comment]
If you're wanting YAML you need to do

```
-o yaml
```

instead of -o json

**Comment by Fyb3roptik** [comment]
In either case I am not experiencing this. Please check your config file
