### ISSUE TITLE
Not able to see API information using yaml file

### ISSUE THREAD

**Issue by kkashyap1707** [Fyb3roptik/swaggomnia#3]
### Expected behavior
Index.html file should contains information of the api's.

### Current behavior
Not able to see any API's information. It says "Failed to load API definition."

### Steps to reproduce the behavior
Put yaml file in /dist folder
Start the server using npm run
Go to http://localhost:3002/index.html

![Screenshot from 2019-06-06 16-22-32](https://user-images.githubusercontent.com/4715140/59027857-bcb56100-8877-11e9-8e59-bf07856ac058.png)

**Comment by Fyb3roptik** [comment]
This is not in scope for the project. You simply take the yaml file and import it to swaggerhub
