### ISSUE TITLE
Not getting correct output

### ISSUE THREAD

**Issue by Saceone** [Fyb3roptik/swaggomnia#4]
I have the following structure in insomnia:
- Folder 1
---- request 1 (GET)
- Folder 2
---- request 2 (POST)

This is what I am getting from swaggomnia:
tags:

- name: "Folder 1"
  description: ""

- name: "Folder 2"
  description: ""

Nothing about the requests inside the folders. What am I doing wrong?

**Comment by Fyb3roptik** [comment]
Do you have your export from insomnia that i can review?

**Comment by Fyb3roptik** [comment]
Closing since I cannot debug. Please respond if you can get me something to debug
