### ISSUE TITLE
which versions of insomania exort it works with?

### ISSUE THREAD

**Issue by MohitKS5** [Fyb3roptik/swaggomnia#6]
### Expected behavior
show body as example request?
### Current behavior
doesn't displays body params
### Steps to reproduce the behavior
convert any insomania v4 file
Basically I am asking if this issue was solved?
https://github.com/mlabouardy/swaggymnia/issues/9

**Comment by Fyb3roptik** [comment]
I am actually about to ramp up development on this again to get it updated as I will be doing some API doc exporting for swagger real soon. I will keep you posted!

**Comment by gnidustotalus** [comment]
Any news?

**Comment by Fyb3roptik** [comment]
I am working on this right now. I am also solving the issue of variables not having their value input correctly.
