### ISSUE TITLE
Swaggomnia is not compatible with 64-bit Win

### ISSUE THREAD

**Issue by IuliiaSafonova** [Fyb3roptik/swaggomnia#8]
### Expected behavior
creating swagger file

### Current behavior
C:\Swagger>swaggomnia generate -i GraphQL.json -c config.json -o yaml
This version of C:\Users\i.safonova\Downloads\swaggomnia.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.

### Steps to reproduce the behavior
generate swagger file with swaggomnia
swaggomnia generate -i GraphQL.json -c config.json -o yaml

**Comment by Fyb3roptik** [comment]
I just released a newer build. Please try that

**Comment by Fyb3roptik** [comment]
Please check the new release as well as the new config file format in the README

https://github.com/Fyb3roptik/swaggomnia/releases/tag/2.0.0
