### ISSUE TITLE
Structural issues in generated swagger yaml file

### ISSUE THREAD

**Issue by samair** [Fyb3roptik/swaggomnia#9]
**Describe the bug**
Many Syntax errors after converting a insomnia json to swagger yaml

**To Reproduce**
1.  Key in the configurations:
    used the below:
    {
  "title" : "Product Service",
  "version" : "0.1",
  "basePath" : "https://xxxx.amazonaws.com/dev/",
  "description" : "API description"
  }
2. Run the command:
    swaggomnia generate --insomnia Insomnia_2020-02-21.json --config config.json --output yaml
3. Open the generated yaml in https://editor.swagger.io/

4. Observed many syntax errors
    Example:

>    Structural error at paths
> should only have path names that start with `/`
> Jump to line 13

**Expected behavior**
No Structural errors should be seen

** Screenshots**
<img width="1438" alt="Screenshot 2020-02-21 at 7 07 54 PM" src="https://user-images.githubusercontent.com/22045045/75039041-d407ad80-54dd-11ea-8d53-777ad01a7e79.png">

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.2

**Comment by Fyb3roptik** [comment]
Did you update your config? The config has changed. Also please send me the exported insomnia file so I can take a look at it

**Comment by samair** [comment]
[Archive.zip](https://github.com/Fyb3roptik/swaggomnia/files/4238853/Archive.zip)
It has config, insomnia export and generated swagger,
Another thing i noticed, the query parameters are wrong as well.

Advise me if i am not setting things properly in Insomnia...
Great initiative to keep this working btw!
Cheers!
Sameer

**Comment by samair** [comment]
I found the problem why "query parameters" do not migrate to swagger.yaml. Ok  for a PR ?

**Comment by Fyb3roptik** [comment]
Did you put the parameters in the URL? If so, that is not how it is done. They need to be in the Query section

**Comment by samair** [comment]
I did put them in query section, the problem seems to be the template used. I fixed it locally by updating the template.

Will send you a Pull Request with the fix.

**Comment by Fyb3roptik** [comment]
ok shoot it over. I will look at the base_url stuff as that should not be the case

**Comment by Fyb3roptik** [comment]
Just started a gitter https://gitter.im/swaggomnia

**Comment by Fyb3roptik** [comment]
Release 2.0.1 has these fixes
